### ISSUE TITLE
DEPRECATED Action signature

### ISSUE THREAD

**Issue by kputland** [getcarina/dvm#103]
Fresh install 2016-05-11 20:50 UTC
OSX: 10.11.5 Beta (15F28b)

Eng-MacBook-Pro:~ karl$ dvm ls
->	system (1.9.1)
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by carolynvs** [comment]
Looks like a small enough signature change. I'll look at this today.

**Comment by carolynvs** [comment]
Okay the main change is that all command actions should return error. However I don't like how it handles the error, we have much nicer stuff in util right now with coloring, formatting, etc. So I'm going to keep what we have and just return nil from everything.

**Comment by carolynvs** [comment]
@kputland Thank you for reporting this problem! I've released dvm 0.4.2, just run `dvm upgrade` and you should be all set.

**Comment by kputland** [comment]
Looks good now. No more error.
Thanks.




Eng-MacBook-Pro:~ karl$ dvm ls

->
system (1.9.1)

DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See

https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

Eng-MacBook-Pro:~ karl$ dvm upgrade

Upgrading to dvm 0.4.2...

DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See

https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

Eng-MacBook-Pro:~ karl$ dvm ls

->
system (1.9.1)

Eng-MacBook-Pro:~ karl$ 








On May 12, 2016, at 9:46 AM, Carolyn Van Slyck <notifications@github.com> wrote:


@kputland Thank you for reporting this problem! I've released dvm 0.4.2, just run
dvm upgrade and you should be all set.
—
You are receiving this because you were mentioned.
Reply to this email directly or 
view it on GitHub
