### ISSUE TITLE
DVM … not doing anything.

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [getcarina/dvm#104]
(Possibly the least-descriptive Issue title I've ever written?)

So, I've installed DVM via the curl-sh snippet (also, [plz don't](https://github.com/getcarina/dvm/issues/105) :P); and …

    > dvm ls-remote
    > echo $?      
    0
    > dvm install 1.10.3
    > echo $?
    0
    > dvm current
    system (1.11.1)
    DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

Each of those commands takes a moment to evaluate, but produces no output, and has no effect.

I'm on OS X 10.11.3; using the system Docker client from Homebrew.

**Comment by carolynvs** [comment]
Thanks for reporting this! I am consolidating it into a single issue #103 and will be looking at it today.

**Comment by carolynvs** [comment]
Nevermind reopening. 😊  That last warning message threw me off but I don't think they are related. Even when dvm prints that "deprecated" message, it should have done _something_.

**Comment by carolynvs** [comment]
Would you please run `dvm --debug install 1.10.3` and post the output?

Also is this a local build? I noticed that you are cloning the repo and may not have used the current dvm installation routine (due to noted security concerns).

**Comment by carolynvs** [comment]
I was able to reproduce this behavior when my `DVM_DIR` environment variable didn't match my local clone's location. These are the steps that I use when testing, maybe they will help.

1. `cd ~/src/github.com/getcarina/dvm`
2. `make`
3. `export DVM_DIR=$PWD`
3. `source dvm.sh`

**Comment by ELLIOTTCABLE** [comment]
Hm. So, I was in *a* local-clone of dvm: I've originally installed as described in #101; but after discovering that that was unsupported, I removed `~/.dvm` entirely, and installed in the sanctioned method: so I have a `~/.dvm/dvm.sh`, `~/.dvm/dvm-helper`, and `~/.dvm/bash_completion`. Nothing else.

**Comment by carolynvs** [comment]
That is really odd! I don't see a code path where something would not get printed after it repeated back the original command when you ran `dvm --debug install 1.10.3`...

How about running the following and sending back the output?

```
source /Users/ec/.dvm/dvm.sh
echo $DVM_DIR
dvm --version
dvm --debug install 1.10.3
/Users/ec/.dvm/dvm-helper/dvm-helper --debug --shell bash --dvm-dir=/Users/ec/.dvm install 1.10.3
```

**Comment by ELLIOTTCABLE** [comment]
Okay, so, I can no longer reproduce this issue, unfortunately. |=

I'm closing, unless I can convince it to show up again.

(Also, 'ullo from the South Loop, @carolynvs. :P)
