### ISSUE TITLE
alternate mirrorURL

### ISSUE THREAD

**Issue by andrefernandes** [getcarina/dvm#108]
Docker binary download could come from a known mirror, inside corporate LAN.

Can make a PR if you agree...

**Comment by rgbkrk** [comment]
Totally agree. I did the same thing for `nvm` back in the day. I thought for sure we had that here, though that must pre-date the whole `dvm-helper` binary.

**Comment by andrefernandes** [comment]
In dvm-helper code the variable is indeed named "mirrorURL", but its value is now hard-coded. :)

**Comment by carolynvs** [comment]
Sorry Kyle, I totally Godzilla'd dvm when switching to go....

**Comment by rgbkrk** [comment]
The beauty is that we can now accept new contributions to bring it back. :wink:

We were overly willing to accept the ability to have this work on Windows cleanly too, so I think having to reimplement it was fine. :smile:

**Comment by carolynvs** [comment]
Fixed in #109 and will be available once I push out a new dvm release.
