### ISSUE TITLE
Docker 1.11 filename change on Darwin

### ISSUE THREAD

**Issue by coreypobrien** [getcarina/dvm#111]
The filename for docker binaries on Darwin now includes a tgz extension for 1.11+ but dvm is assuming no extension:

The 1.10.3 url is `https://get.docker.com/builds/Darwin/x86_64/docker-1.10.3`
The 1.11.1 url is `https://get.docker.com/builds/Darwin/x86_64/docker-1.11.1.tgz`

**Comment by jnoller** [comment]
@carolynvs ^

**Comment by adrianotto** [comment]
The tar file contains docker/docker, so dvm will need some additional logic to unpack that, and place the binary where it belongs.

**Comment by carolynvs** [comment]
@coreypobrien This was fixed in [dvm 0.4.0](https://github.com/getcarina/dvm/releases/tag/0.4.0). If you still encounter problems after running `dvm upgrade`, please reopen this issue and I'll help troubleshoot.

**Comment by jnoller** [comment]
@adrianotto

**Comment by adrianotto** [comment]
Confirmed, running "dvm update" does resolve this.
