### ISSUE TITLE
download.getcarina.com outage?

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/dvm#113]
```
$ curl -sL https://download.getcarina.com/dvm/latest/install.sh
```

is returning _nothing_

**Comment by danvaida** [comment]
+1

**Comment by carolynvs** [comment]
Thanks for the heads up, seems to be cert related. I'll get that back up asap.

**Comment by carolynvs** [comment]
I've redeployed to a healthy docker host and added monitoring so that my team is pinged if it goes down again.
