### ISSUE TITLE
Doesn't include docker-machine

### ISSUE THREAD

**Issue by pcgeek86** [getcarina/dvm#125]
DVM doesn't seem to include `docker-machine`, which I need to manage Docker Hosts. Is this supposed to work already, and if not, can it be added?

**Comment by carolynvs** [comment]
`dvm` is intended to distribute the docker client binary as that is what people are most often switching between. For example, one host is on 1.9.1 and another host is updated as soon as new shiny builds come out.

So far I haven't seen the need to switch between `docker-machine` client versions, so I do not plan to distribute it via dvm. Installing and updating docker machine is a task better suited for either the Docker Toolbox installer, or their homebrew formula.

I'm closing for now but feel free to leave a comment with your use case and why the above mechanisms aren't sufficient.

**Comment by pcgeek86** [comment]
@carolynvs Thanks Carolyn -- yeah I'm seeing a consistent experience with what you talked about in your comment. The most common need is to switch between Docker binaries, and not quite as much Docker Machine. I think I can deal with this for the time being, but I will post back here if I can come up with a concrete use case. Thanks!!! :whale: :whale2:
