### ISSUE TITLE
Getting dvm to work with zsh

### ISSUE THREAD

**Issue by lborg019** [getcarina/dvm#131]
After installing it, in order to make it work with zsh (oh-my-zsh in my case) all I needed to do was add

``` bash
source $HOME/.dvm/dvm.sh
```

to the .zshrc file.
Since I'm running oh-my-zsh, I put this line right before

``` bash
source $ZSH/oh-my-zsh.sh
```

and it works nicely.

**Comment by carolynvs** [comment]
I'm glad to hear that it works! Since you opened this issue is there something that needs to change in the readme or code?

**Comment by lborg019** [comment]
It might be helpful to have such instructions on the readme as an optional step. Since we already mentioned it here, it's up to you.

Remember; these instructions are for .zsh users who do not want to type
```bash
~$ source /.dvm/dvm.sh
```
every time they need to use dvm.
Users should be aware that the more scripts/environment variables are added to the terminal's boot, the slower it will load.

**Comment by carolynvs** [comment]
Gotcha thanks! I'll add that to the readme.
