### ISSUE TITLE
Can not alias system version.

### ISSUE THREAD

**Issue by chrisLeeTW** [getcarina/dvm#132]
as title, I can not alias system version.

> #> dvm alias default system
> Aliased default to system.
> 
> #> dvm ls-alias
>               default -> 0.0.0
> 
> #> dvm use default                                                                                                                                                              
> default is not installed. Installing now...
> Version default not found - try `dvm ls-remote` to browse available versions

It is not showing the right version & `dvm use` command also not work correctly.

dvm version : 
Docker Version Manager version 0.6.3 (65c380cf2079fa5387ca49c7b5552ae4e2ec3b77)

install method : brew

OS : Mac OS X El Capitan

**Comment by carolynvs** [comment]
Aliasing to another alias (system) is not supported and can only be defined to a specific version number.

You can use `dvm use system` to switch to the system installation of the Docker client.
