### ISSUE TITLE
Feature Discussion: Add "dockerbin" as a dvm feature?

### ISSUE THREAD

**Issue by LongLiveCHIEF** [getcarina/dvm#134]
I've been working on a project I call [dockerbin](https://gitlab.com/HackerHappyHour/dockerbin), and I've come to wonder if the functionality of dockerbin would be a better to include/pair with `dvm`, or if it should remain two separate projects.

Before I share any of my specific thoughts, I'm curious in your opinion of this idea.  Either way, I believe these two purposes are going to work well together.

**Comment by carolynvs** [comment]
dvm is focused on getting the appropriate version of the docker client binary onto your machine and accessible from the current shell session. I'm not sure I understand how you'd like to pair dvm with dockerbin?
