### ISSUE TITLE
Confusion in the "Install Docker" section

### ISSUE THREAD

**Issue by JetForMe** [getcarina/dvm#135]
I had some confusion while installing Carina using homebrew on macOS. Namely, the first section has instructions for macOS/homebrew and macOS/NOT-homebrew. But this section is a little unclear on whether or not we're supposed to do both macOS steps (the brew install and the curl command), or just the one.

It seems both are necessary, as without the curl command, there is no "docker" command. But it seems like docker should be installable via brew only, without a separate curl command. In fact, brew install dvm does install dvm, and dvm-helper, under /usr/local/Cellar/dvm, so I feel like I've got some redundant installation right now.

**Comment by carolynvs** [comment]
The sections for "Mac OS with Homebrew", "Mac OS and Linux" (without Homebrew) and "Windows" are mutually exclusive. So if you have homebrew, you only run the installation commands from that section. I'll update the readme to make that more clear.

After you have run the command to install dvm, and then load dvm.sh, you must then use dvm to get the docker client by running `dvm install X.Y` where `X.Y` is a docker version, like 1.11.1.

So if you have homebrew setup looks something like this from end to end:

```bash
~$ brew install dvm
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
dspdfviewer                                                    jenkins

==> Downloading https://homebrew.bintray.com/bottles/dvm-0.6.4.el_capitan.bottle.tar.gz
######################################################################## 100.0%
==> Pouring dvm-0.6.4.el_capitan.bottle.tar.gz
==> Caveats
dvm is a shell function, and must be sourced before it can be used.
Add the following command to your bash profile:

    [[ -s "$(brew --prefix dvm)/dvm.sh" ]] && source "$(brew --prefix dvm)/dvm.sh"

To enable tab completion of commands, add the following command to your bash profile:
    [[ -s "$(brew --prefix dvm)/bash_completion" ]] && source "$(brew --prefix dvm)/bash_completion"

==> Summary
🍺  /usr/local/Cellar/dvm/0.6.4: 7 files, 6M
~$ source "$(brew --prefix dvm)/dvm.sh"
~$ dvm install 1.11.1
Installing 1.11.1...
Now using Docker 1.11.1
~$ docker --version
Docker version 1.11.1, build 5604cbe
```
