### ISSUE TITLE
Getting dvm to work on Windows CMDER (ConEmu)

### ISSUE THREAD

**Issue by lborg019** [getcarina/dvm#137]
For my windows machine I installed dvm running the same powershell command from the readme:

` > Invoke-WebRequest https://download.getcarina.com/dvm/latest/install.ps1 -UseBasicParsing | Invoke-Expression`

but since I use [CMDER](https://github.com/cmderdev/cmder) I went to my CMDER folder and modified my user-startup.cmd file in order to get it working. In CMDER/config/ open your user-startup.cmd and add the following line:
`@set PATH=%PATH%;C:\Users\username\.dvm`
(substituting 'username' for your username, or the entire `C:\...` path to the path corresponding to your .dvm folder) and it works!
👍

**Comment by carolynvs** [comment]
HOT! I use conemu instead of cmder, but that's good to know how to get it automatically loaded. I'll add that to the readme.

Thanks for sharing!

**Comment by carolynvs** [comment]
I was inspired to try out CMDER and after installing it, dvm just worked without modifying CMDERs files, it just picked it up from my Windows PATH. Is this extra step for CMDER required or just for people who didn't want to change their Windows PATH?

**Comment by lborg019** [comment]
I'm not sure now; it could be an update change or specific setup to CMDER.
My full version did not work straight away so I had to fix it. I'll reply if I find out anything.
