### ISSUE TITLE
PATH is not updated with mintty on Windows

### ISSUE THREAD

**Issue by dessant** [getcarina/dvm#146]
`PATH` stays the same with mintty, but it is updated correctly with cmd. Tested with 0.6.4 and 0.6.5 on Windows 10.

### What didn't work?
```
$ echo $PATH
/C/Python34:/C/Python34/Scripts

$ dvm --debug use
The dvm home directory is: C:\Users\prc\.dvm\
dvm use 1.11.2
Checking if version is installed: 1.11.2
C:\Program Files\Docker Toolbox\docker.exe -v output: Docker version 1.13.0, build 49bf474

Checking version: 1.11.2
Version 1.11.2 is installed
Writing to C:\Users\prc\.dvm\.tmp\dvm-output.cmd...
PATH=C:\Users\prc\.dvm\bin\docker\1.11.2;C:\Python34;C:\Python34\Scripts
Now using Docker 1.11.2

$ echo $PATH
/C/Python34:/C/Python34/Scripts
```

```
$ dvm --version
Docker Version Manager version 0.6.5 (3c707bd)
```

How did you install dvm (command-line,chocolatey,homebrew)?

`Invoke-WebRequest https://download.getcarina.com/dvm/latest/install.ps1 -UseBasicParsing | Invoke-Expression`

**Comment by carolynvs** [comment]
At this time dvm on Windows only supports CMD and PowerShell.  I've opened an issue asking for help to address this gap: https://github.com/getcarina/dvm/issues/147
