### ISSUE TITLE
dvm use docker-host-version

### ISSUE THREAD

**Issue by everett-toews** [getcarina/dvm#17]
It would be super helpful if dvm could detect the version in use by `DOCKER_HOST`, download it automatically, and use that.

    $ dvm use docker-host-version
    ######################################################################## 100.0%
    Now using Docker 1.6.1    

`docker-host-version` is a bit verbose and probably not the best name for this thing.

**Comment by smashwilson** [comment]
I think @rgbkrk wanted to support something like a `DOCKER_VERSION` env var for things like that; see #7. We definitely want something like that though.

**Comment by rgbkrk** [comment]
We might be able to do the same fingerprinting that docker-py does for its auto mode, in addition to looking for the DOCKER_VERSION.

**Comment by smashwilson** [comment]
Like pulling `docker version -f '{{.Server.Version}'` automatically?

**Comment by rgbkrk** [comment]
Yeah, but over the API (btw, the format flag doesn't exist in 1.6.1).

The annoying part will be certs with non-trivial curl/wget.

**Comment by rgbkrk** [comment]
I was really hoping to use 

```
curl $( echo $DOCKER_HOST | sed 's/tcp/https/')/version --cert $DOCKER_CERT_PATH/cert.pem --key $DOCKER_CERT_PATH/key.pem --cacert $DOCKER_CERT_PATH/ca.pem
curl: (58) SSL: Can't load the certificate "/Users/rgbkrk/trythingsout/dekiagari/cert.pem" and its private key: OSStatus -25299
```

but as @everett-toews has already reported (https://github.com/docker/docker/issues/16107), this isn't a happy place in OS X. I'd have to convert the certs to a different format.

**Comment by carolynvs** [comment]
This is how dvm interacts with DOCKER_VERSION which is included in the Carina credentials file. Can we close this issue or is there more to do?

```bash
$ source ~/Downloads/mycluster/docker.env
$ dvm use
Now using Docker 1.8.3
```

**Comment by rgbkrk** [comment]
Now that I've closed it, I realize that @everett-toews is also asking for auto-download if not already installed. We won't do that but `$DOCKER_VERSION` is recognized.

**Comment by everett-toews** [comment]
Ummmmm...

```
$ dvm use 1.8.0
1.8.0 is not installed. Installing now...
Installing 1.8.0...
Now using Docker 1.8.0
```

Looks like auto-download got implemented (which I'm okay with).

**Comment by everett-toews** [comment]
A separate issue was opened for auto-download at #19

**Comment by rgbkrk** [comment]
I'm totally wrong and that's totally cool.
