### ISSUE TITLE
dvm use to download automatically

### ISSUE THREAD

**Issue by everett-toews** [getcarina/dvm#19]
It would be nice to have dvm use download missing version automatically rather than having the user run another command.

Instead of

    $ dvm use 1.8.0
    N/A: version "N/A" is not yet installed

do 

    $ dvm use 1.8.0
    ######################################################################## 100.0%
    Now using Docker 1.8.0

**Comment by smashwilson** [comment]
:+1:

I think I'd prefer to hide it behind another flag to make it explicit:

```
dvm use --install 1.8.0
```

**Comment by rgbkrk** [comment]
totes happens now
