### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by smashwilson** [getcarina/dvm#2]
How many of nvm's commands do we want to support initially?

For a first release, it seems to me that we only need:

- [x] `dvm help`
- [x] `dvm --version`
- [x] `dvm use` - #3
- [x] `dvm install`
- [x] `dvm ls`
- [x] `dvm ls-remote`

These ones still make sense, so maybe as a second wave:

- [x] `dvm uninstall`
- [X] ~~`dvm run`~~ not doing this
- [x] `dvm current`
- [ ] `dvm version` - comes after the first release
- [ ] `dvm version-remote` - also after the first release
- [x] `dvm deactivate`
- [x] `dvm alias`
- [x] `dvm unalias`
- [ ] `dvm unload` - it's in our help, but apparently not working or implemented
- [ ] `dvm which` - it's in our help, but apparently not working or implemented

The remaining commands, like `dvm reinstall-packages`, don't make much sense to me.

What do you think?

**Comment by rgbkrk** [comment]
I certainly agree with the 6 commands you listed first. I'm not sure how we'll do `dvm ls-remote` because I can't seem to find an index with all available binaries.

**Comment by smashwilson** [comment]
> I'm not sure how we'll do dvm ls-remote because I can't seem to find an index with all available binaries.

Yeah, that's the tough one. Can we do :sparkles: magic :sparkles: with the GitHub releases?

**Comment by rgbkrk** [comment]
To answer the question I never did here, "yes, we can use GitHub releases".

I'm a fan of ripping `run` and `exec` out for now.

**Comment by rgbkrk** [comment]
Updated a few of the above

**Comment by rgbkrk** [comment]
We're in a good state here and can open issues for individual ones we want.
