### ISSUE TITLE
dvm using correct docker version?

### ISSUE THREAD

**Issue by everett-toews** [getcarina/dvm#33]
I removed my ~/.dvm dir as I could have sworn I read somewhere that I need to do that when switching to the new binary. 

```
~ $ which docker
/usr/local/bin/docker

~ $ docker version
Client:
 Version:      1.8.2

~ $ dvm use 1.8.0
Now using Docker 1.8.0

~ $ which docker
/usr/local/bin/docker

~ $ docker version
Client:
 Version:      1.8.2

~ $ dvm --version
Docker Version Manager version 0.1.0 (9334dd1)
```

On Mac OS X 10.11 

@carolynvs

**Comment by rgbkrk** [comment]
```
$ dvm use 1.8.2
1.8.2 is not installed. Installing now...
Installing 1.8.2...
Now using Docker 1.8.2
bash: /Users/kyle6475/.dvm/.tmp/dvm-output.sh: line 1: syntax error near unexpected token `('
bash: /Users/kyle6475/.dvm/.tmp/dvm-output.sh: line 1: `export PATH=/Users/kyle6475/.dvm/bin/docker/1.8.2:/Users/kyle6475/amphora:./bin:/usr/local/bin:/usr/local/sbin:/Users/kyle6475/.dotfiles/bin:/Users/kyle6475/.nvm/versions/node/v4.1.0/bin:/Users/kyle6475/bin:/Applications/Kitematic (Beta).app/Contents/Resources/resources:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/usr/local/opt/go/libexec/bin:/usr/local/opt/go/libexec/bin:/Users/kyle6475/.rbenv/bin:/Users/kyle6475/.rbenv/shims:/Users/kyle6475/code/bin'
07:45:02 rgbkrk@lack ~/.dvm$ ls /usr/local/munki/
```

**Comment by rgbkrk** [comment]
Last part needs some quotes in the output. I'll fix that now.

**Comment by everett-toews** [comment]
Curses. I did something wacky here. I downloaded the dvm-helper and used it like dvm.

Basically

```
wget -O dvm https://github.com/getcarina/dvm/releases/download/0.1.0/dvm-helper-darwin-amd64
chmod u+x dvm
./dvm blah
```

I got it into my head that dvm-helper somehow replaced dvm

:facepalm:

From my view this issue is invalid.

**Comment by rgbkrk** [comment]
Something tells me `dvm-helper` should be in a separate repo so people don't get confused by releases ("oh I should download this!").

**Comment by everett-toews** [comment]
That's totally me. Downloading random binaries and `chmod u+x yeehaw` is the new `curl -s https://raw.githubusercontent.com/random/repo/master/yeehaw.sh | sh`

**Comment by carolynvs** [comment]
Doh sorry the README explains how to install. Basically I have people execute install.sh / install.ps1 which gets you the wrapper shell script(s). Then the wrapper checks for the dvm-helper binary and downloads it for you.

Take a look at the README and let me know if it's not clear.

**Comment by everett-toews** [comment]
My bad. I totally bypassed the README.
