### ISSUE TITLE
Automate release using github-release

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/dvm#36]
See https://github.com/getcarina/carina/blob/master/release.sh for an example of using `github-release`.

**Comment by carolynvs** [comment]
As part of this, I'll look into use Make instead of build scripts.

**Comment by carolynvs** [comment]
@rgbkrk I notice that Carina only builds for amd64. At the moment I was doing 386 as well but honestly don't know who would need that?

**Comment by rgbkrk** [comment]
Yeah I was going to support 386 if someone asked, figuring amd64 was the way to go until then.

**Comment by carolynvs** [comment]
Sounds good. I'm going to follow suit since compiling and uploading 6 binaries is slow. :smile:
