### ISSUE TITLE
Break platform specific functionality of dvm-helper up

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/dvm#39]
Go lets you build certain things for certain platforms. For some of the `if runtime.GOOS == X` branches, we can make specific functions for each platform, similar to how `carina` does it by relying on functions declared in https://github.com/getcarina/carina/blob/master/credentials_windows.go and https://github.com/getcarina/carina/blob/master/credentials_nix.go.

**Comment by carolynvs** [comment]
Yeah... I knew it was an ugly kludge when I did it. :smile:  I'll look at splitting up the `if runtime` stuff into separate files tomorrow.

**Comment by rgbkrk** [comment]
Heh, working is better than anything. :)
