### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by carolynvs** [getcarina/dvm#41]
The cli package provides bash completion but isn't hooked up at all. I'd like to do something like `rack init` which configures it for you.

I'm not sure if going through the wrapper scripts will cause us grief or not though...

**Comment by rgbkrk** [comment]
We could bring back the old bash completion. It was lovely.

**Comment by rgbkrk** [comment]
Codegangsta cli's bash completion won't give us some of the advanced stuff we did for tab completion on `dvm use` for instance:

```
$ dvm use 1.[TAB]
1.8.2 1.6.1
$ dvm use 1.8[TAB]
$ dvm use 1.8.2
```

**Comment by carolynvs** [comment]
May want to hold off of this and #38 until we switch to kingpin. I am hoping it will provide much better completion functionality.

**Comment by rgbkrk** [comment]
This was brought in via #63.
