### ISSUE TITLE
Support Bash on Windows

### ISSUE THREAD

**Issue by carolynvs** [getcarina/dvm#42]
I'm not sure how easy this will be. Go knows it's running on Windows, and anything it generates will use Windows paths, but would need to be evaluated in cygwin/mingw which needs UNIX paths.

I wouldn't want to share dvm.sh though. If we go down this route, it should be separate and install.ps1 would download a different dvm.sh for windows than install.sh installs for linux/mac.

**Comment by sihorton** [comment]
I just tried this out and it works fine for me already :-) I just opened "Bash on Ubuntu on Windows", then
curl -sL https://download.getcarina.com/dvm/latest/install.sh | sh
dvm ls-remote
dvm install 1.12.3
docker -H tcp://0.0.0.0:2375 info

The -H tcp://0.0.0.0:2375 option means the client is connecting to docker on windows on the local machine (running on port 2375). So this is a nice way to script docker from bash while running windows.

**Comment by carolynvs** [comment]
Huzzah! Glad to hear that it works well with Bash on Windows! 🎉
