### ISSUE TITLE
Handle upgrades

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/dvm#44]
We need a nice way to handle upgrades.

**Comment by carolynvs** [comment]
We could take advantage of how the binary communicates with the shell (via the temp file). `dvm upgrade` would put  `curl -s http://download.getcarina.com/getcarina/dvm/latest/install.sh | sh` or the appropriate powershell command in the dvm-output file and would be automatically execute by the wrapper script.

**Comment by carolynvs** [comment]
After thinking about it last night, what I suggested above would work but could be even more simple. I don't believe linux/mac has a restriction about copying over an active file? So `dvm upgrade` would download the file and overwrite on mac/linux. On Windows it would download the file to the `.tmp` folder and have the wrapper script copy it.

**Comment by rgbkrk** [comment]
> After thinking about it last night, what I suggested above would work but could be even more simple. I don't believe linux/mac has a restriction about copying over an active file? So dvm upgrade would download the file and overwrite on mac/linux. On Windows it would download the file to the .tmp folder and have the wrapper script copy it.

:+1:

**Comment by rgbkrk** [comment]
Amusingly, when I wrote this I meant more as a way of upgrading from old to current gen. Now we're in a wonderful state of upgrade land.

**Comment by rgbkrk** [comment]
:smile:
