### ISSUE TITLE
Fix detection of 86 vs 64 on Windows

### ISSUE THREAD

**Issue by carolynvs** [getcarina/dvm#75]
See https://github.com/getcarina/carina/issues/83

**Comment by carolynvs** [comment]
@zack-shoylev Can you run the following commands to give more info about your PowerShell bits?

```
echo [System.Environment]::Is64BitOperatingSystem
echo [System.Runtime.InterOpServices.Marshal]::SizeOf([System.IntPtr])
```

**Comment by zack-shoylev** [comment]
I already upgraded to PS version 4 and everything seems to be working. So I can confirm that the problems were limited to just that older version. I would suggest just adding a note to upgrade PS, it was a single update with few prereqs.

**Comment by carolynvs** [comment]
@zack-shoylev Awesome, thanks for checking. Closing this bug and the doc / detection of old powershell versions will be added in #76 .
