### ISSUE TITLE
Authenticate github api calls to avoid rate limit

### ISSUE THREAD

**Issue by carolynvs** [getcarina/dvm#78]
Once you hit the rate limit, you may end up waiting an hour before you can install a new version... It would be nice if when we hit the limit, we could prompt the user to authenticate to "keep playing". Once they authenticate, we can save that in the carina config to use again.

https://github.com/google/go-github#authentication explains how to pass in the token.

**Comment by rgbkrk** [comment]
Sounds good to me.

That's what `carina` does right now with `$GITHUB_TOKEN`. It's the sam env var used by homebrew and quite a few others too.

https://github.com/getcarina/carina/blob/46b8ab092bfe2c8972eaee9b4249b22ee11a413a/version/releases.go#L58

**Comment by carolynvs** [comment]
Excellent! I'll rip that off then. :smile:
