### ISSUE TITLE
dvm ls not showing system

### ISSUE THREAD

**Issue by JoakimLofgren** [getcarina/dvm#81]
To behave more like `nvm` the ls command should also show system.
Since you can do `dvm use system` the `dvm ls` should also show system in the outputted list.

E.g.
```shell
$ nvm ls
->       v5.0.0
         system
default -> v5.0.0
node -> stable (-> v5.0.0) (default)
stable -> 5.0 (-> v5.0.0) (default)
```

**Comment by carolynvs** [comment]
This may be a bug as it should work (see below). I'm looking at it now...

When you run `dvm ls`, if `docker` is available on the current PATH, and is not located under the dvm directory, it is considered to be the system dvm. The output in this case will look as follows:

![d3f0f39a-7d7f-11e5-87b5-1bda5ffe4859](https://cloud.githubusercontent.com/assets/1368985/12616441/d17f3462-c4d0-11e5-81ee-fda0b8424d80.png)

**Comment by carolynvs** [comment]
Thanks for the heads up! I broke this in v0.3 with 5627f2231e21133402a3545ee3e9b683ceb3f282. I'll get a fix released today.
