### ISSUE TITLE
Maintenance, including others

### ISSUE THREAD

**Issue by rgbkrk** [getcarina/dvm#89]
We've had a few great PRs from folks not employed by Rackspace/Carina. `dvm` itself outgrew on my own org then moved over to getcarina and is generally a tool for everyone. Would it be alright for us to welcome others in maintaining `dvm` itself, in hopes that it is generally a good tool for the community?

**Comment by carolynvs** [comment]
I think that would be great. 👍

**Comment by rgbkrk** [comment]
Alright, I've begun adding some dutiful committers:

* @ELLIOTTCABLE
* @ibigbug
* @glyph

Welcome aboard!

As always, make sure to open PRs (no pushing direct to master). Awesome having you.
