### ISSUE TITLE
Improve version sorting

### ISSUE THREAD

**Issue by carolynvs** [getcarina/dvm#92]
Right now when printing versions, we are sorting based on the version string. It would be nice to sort based on the semantic version instead.

**expected**
```
$ dvm ls-remote
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
1.10.0
1.10.1
1.10.2
1.10.3
```

**actual**
```
$ dvm ls-remote
1.10.0
1.10.1
1.10.2
1.10.3
1.7.1
1.8.0
1.8.1
1.8.2
1.8.3
1.9.0
1.9.1
```

**Comment by rgbkrk** [comment]
That would be much improved!

**Comment by rgbkrk** [comment]
I do think later versions should appear at the bottom. In case it's ever really long, it shows the most recent above the user's next prompt.

**Comment by carolynvs** [comment]
@rgbkrk  Where should aliases show up in the sorted list?

**Option 1: At the bottom**
What we do today (but with semver sorting fixed)
```
	1.6.1
	1.8.1
	1.8.2
	1.8.3
	1.9.1
	1.10.1
	1.10.2
	1.10.3
	experimental (1.10.0-dev, build 0cdc96c)
->	system (1.10.3)
```

**Option 2: Included in the sorted list**
Continue to show the alias before the version number. This way the the first thing you see is what you can type into a `dvm use X` command
```
	1.6.1
	1.8.1
	1.8.2
	1.8.3
	1.9.1
	experimental (1.10.0-dev, build 0cdc96c)
	1.10.1
	1.10.2
	1.10.3
->	system (1.10.3)
```

**Option 2: ALL NUMBERS**
```
	1.6.1
	1.8.1
	1.8.2
	1.8.3
	1.9.1
	1.10.0-dev, build 0cdc96c (experimental)
	1.10.1
	1.10.2
	1.10.3
->	1.10.3 (system)
```

**Comment by carolynvs** [comment]
I'm going to go with Option 2 for now, as it's the easiest to implement. :smile:
