### ISSUE TITLE
Windows install on new Windows 10 box fails with error "The response content cannot be parsed because the Internet Explorer engine is not available..."

### ISSUE THREAD

**Issue by DonSchenck** [getcarina/dvm#93]
When attempting to install dvm on a new Windows 10 PC, you receive the above error. This is because Internet Explorer (IE) has not been initialized. Even if you have used Microsoft Edge, you will still receive this error.

The solution is to open IE. You will be prompted for security options. Select an option and continue. You can then close IE if you wish; the install will now work.

**Comment by carolynvs** [comment]
Is this because you ran the dvm installer before ever opening IE? Or would someone run into this after having used the machine for weeks? Just trying to figure out if this is a security limitation in PowerShell when downloading web content or a 1 time setup thing.

**Comment by DonSchenck** [comment]
I have been using ONLY Edge, NOT IE. It's because Invoke-Expression is trying to fire off the IE engine, and it hasn't been initialized.

**Comment by carolynvs** [comment]
Thanks for the extra info, I'll try that out with a fresh VM to reproduce and fix. At the very least we can update the instructions with the workaround but hopefully there's a way to trick it into working without it.
