### ISSUE TITLE
dvm.sh doesn't support fish

### ISSUE THREAD

**Issue by 7sDream** [getcarina/dvm#94]
I use fish as my default sh, the current dvm.sh doesn't compatible with it, see below:

![source dvm.sh error](http://ww1.sinaimg.cn/large/88e401f0jw1f2t94noj6kj20et04vwfn.jpg)

But I don't want switch to bash to run dvm and docker command... could you please add support for fish?

I think there are two things to do:

- create a dvm.fish for fish to source
- add "fish" to dvm-helper --shell optional to output a fish-style script

---

As I'm can't wait to use dvm, I write a [dvm.fish](https://gist.github.com/7sDream/69eb3ab8c8ca028c4975e922f356a96b) for temporary use, it has same function as offical dvm.sh, but only convert `export PATH` command in  `$DVM_DIR/.tmp/dvm-output.sh` to fish-style `set PATH` command. I don't know is there any other command that dvm-helper will generate, but it work fine for me now...

But I still want the OFFICAL fish support! Thanks for your work!

**Comment by bdangit** [comment]
@7sDream thats an awesome script to get dvm running in fish.  I needed to edit it to add support for Mac which can be shown here:  https://gist.github.com/bdangit/73203912eb4539f0b5198193257b0104

**Comment by carolynvs** [comment]
Looks like this was fixed by https://github.com/getcarina/libcarina/issues/17
