### ISSUE TITLE
Install of 1.11.0 on Mac/Linux not working

### ISSUE THREAD

**Issue by brint** [getcarina/dvm#95]
Howdy!

dvm is looking to install 1.11.0 by going to https://get.docker.com/builds/Darwin/x86_64/docker-1.11.0. It looks like with this release, they are now having new releases come as a .tgz:

https://get.docker.com/builds/Darwin/x86_64/docker-1.11.0.tgz

All of the older releases for Mac/Linux are still shipping without a `binaryFileExt` and work fine with dvm. I haven't tested with other OS's.

*Edit*: It looks like the older versions I have spot checked can be pulled as a .tgz. It may just be matter of adding `const binaryFileExt string = ".tgz"` and extracting it after it's pulled down.

**Comment by carolynvs** [comment]
Thanks for the heads up!

**Comment by carolynvs** [comment]
Unfortunately the release format is different for Windows vs. Nix and it doesn't look like I can treat new releases the same as the new ones:

* https://get.docker.com/builds/Windows/x86_64/docker-1.11.0.zip exists
* https://get.docker.com/builds/Windows/x86_64/docker-1.10.3.zip does not exist
* https://get.docker.com/builds/Windows/x86_64/docker-1.10.3.exe exists
* https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz has the binary in `docker/docker`
* https://get.docker.com/builds/Linux/x86_64/docker-1.10.3.tgz has the binary in `usr/local/bin/docker`

I have something working for 1.11.0+, so maybe I'll just add a check for the version and use the new release format for those new releases and the old one for previous releases.

**Comment by brint** [comment]
Awww.. :( I was hoping it would be more uniform/easier. Thanks for digging through the issue.

**Comment by carolynvs** [comment]
@brint I have just released dvm 0.4.0, you can get the latest by running `dvm upgrade`. Happy Friday! :sunny:
