### ISSUE TITLE
dvm.sh not working with zsh

### ISSUE THREAD

**Issue by jkachmar** [getcarina/dvm#98]
It looks like `export -f dvm` breaks dvm under zsh.

`source`ing `dvm.sh` gives me the following error:

<img width="416" alt="screen shot 2016-04-21 at 3 32 38 pm" src="https://cloud.githubusercontent.com/assets/8461423/14721857/c4f4cce0-07d6-11e6-9ef3-4700a6e8a20f.png">

Installation/use works as expected under bash:

<img width="434" alt="screen shot 2016-04-21 at 3 38 17 pm" src="https://cloud.githubusercontent.com/assets/8461423/14721937/1c3393b0-07d7-11e6-980b-1efafecc1b63.png">

**Comment by klippx** [comment]
It does work

```sh
╭─mathias.klippinge at SE-C02PPAD5G8WP in ~ using ‹ruby-2.3.0› 16-04-22 - 8:24:38
╰─○ zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
╭─mathias.klippinge at SE-C02PPAD5G8WP in ~ using ‹ruby-2.3.0› 16-04-22 - 8:25:29
╰─○ source .dvm/dvm.sh
dvm () {
	if [ ! -f "$DVM_DIR/dvm-helper/dvm-helper" ]
	then
		echo "Installation corrupt: dvm-helper is missing. Please reinstall dvm."
		return 1
	fi
	DVM_OUTPUT="$DVM_DIR/.tmp/dvm-output.sh"
	rm -f "$DVM_OUTPUT"
	DVM_DIR=$DVM_DIR $DVM_DIR/dvm-helper/dvm-helper --shell sh $@
	if [ -e $DVM_OUTPUT ]
	then
		source $DVM_OUTPUT
	fi
}
╭─mathias.klippinge at SE-C02PPAD5G8WP in ~ using ‹ruby-2.3.0› 16-04-22 - 8:25:39
╰─○ dvm list
	1.9.1
	1.11.0
->	system (1.11.0)
╭─mathias.klippinge at SE-C02PPAD5G8WP in ~ using ‹ruby-2.3.0› 16-04-22 - 8:26:01
╰─○ dvm --version
Docker Version Manager version 0.4.0 (8cdfffe)
```

**Comment by jkachmar** [comment]
That's strange. I stripped my `zshrc` down to the bare minimum to see if some plugin was messing things up, but it's still giving me trouble. I'm usually just using a few, non-invasive, plugins installed with zplug so I didn't think that would be a problem.

For some reason exporting `dvm` as a function (`export -f dvm`) gives me the invalid options error, but exporting it as a shell variable (`export dvm`) isn't an issue. 

I'll try it on my personal computer tonight/over the weekend to see if I can reproduce it somewhere else.

**Comment by weverett** [comment]
I think this may be a zsh issue. I'm having the same problem exporting other functions in zsh right now.

**Comment by 4679** [comment]
same problem

**Comment by andrefernandes** [comment]
It does work on zsh 5.0.x (yosemite OSX), but it is broken for zsh 5.2 (the one installed with brew).

**Comment by rgbkrk** [comment]
Ooooh, thanks for that last update. I'll update my zsh.

**Comment by ibigbug** [comment]
This has been fixed in https://github.com/getcarina/dvm/pull/102 , run `dvm upgrade` should fix your problem.

Feel free to reopen this one if problem still exists :)

**Comment by mattmuller** [comment]
I have this issue. I cant run dvm upgrade because dvm wont run.

Installation corrupt: dvm-helper is missing. Please reinstall dvm.

zsh and homebrew are up to date.

works fine in bash.

**Comment by carolynvs** [comment]
@mattmuller I recommend rerunning the installation to restore the missing files.

**Comment by rapandya** [comment]
Was not working in bash either then I ran below command and it is working in bash now but not in zsh.

[ -f /usr/local/opt/dvm/dvm.sh ] && . /usr/local/opt/dvm/dvm.sh
