### ISSUE TITLE
'docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?' on Amazon Linux

### ISSUE THREAD

**Issue by igorvpcleao** [getcarina/dvm#99]
I've been trying to use dvm along with three different OS's:

- OSx (El-Capitan)

- Ubuntu 16.04

- Amazon Linux

It seems to work fine with all of them, except for Amazon Linux.
After installing, here what happens when I run docker hello-world:

```
[ec2-user@ip-xx-xx-xxx-xxx ~]$ docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

If I use sudo:

```
[ec2-user@ip-xx-xx-xxx-xxx ~]$ sudo docker run hello-world
sudo: docker: command not found
```

Is there any workaround?

Sorry for being a silly question. I just couldn't figure out how to solve it.

Cheers,
Igor

**Comment by carolynvs** [comment]
dvm only handles updating your current PATH so that the right version of the Docker client is used when you run `docker`. When you use `sudo`, you are losing the changes that dvm made to your user's current session. That's why it can't find docker. 😄 

The first error error means that dvm worked fine, i.e. the docker command was found and run sucessfully, but either your Docker environment variables aren't set properly, or there's something else interfering with the connection to your Docker host. If you run `env | grep DOCKER`, do you see the right variables? For example:

```
DOCKER_HOST=tcp://172.99.77.38:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/carolynvs/.carina/clusters/carolynvsrax/test
DOCKER_VERSION=1.10.3
```

If that doesn't help, let me know which AMI you are using and how you are setting the connection to the Docker host and I can try to reproduce.

**Comment by igorvpcleao** [comment]
Hi Carol,

When I run ```env | grep DOCKER``` on AMI, I have nothing as output.

I tried the above command on OSx and Ubuntu as well. Here is the result:

- For OSx I got some nice settings:
```
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.99.100:2376
DOCKER_CERT_PATH=/Users/igor/.docker/machine/machines/default
DOCKER_MACHINE_NAME=default
```

- For Ubuntu, I got the same blank output, but everything is working. So I don't know why it's working on Ubuntu but not on AMI.

Back to AMI, I exported the following variables:
```
export DOCKER_HOST=tcp://localhost:4243 (I also tried tcp://localhost:2376)
export DOCKER_VERSION=1.11.1
```

However, I got the same error. 
Is it necessary to set the DOCKER_CERT_PATH and the DOCKER_MACHINE_NAME?
I'm not using any external container. Only my own machine. On Linux, is the DOCKER_MACHINE_NAME supposed to be any specific value?

Oh, I'm using 'Amazon Linux AMI release 2016.03'.

Thanks a lot!

**Comment by rgbkrk** [comment]
You need to run `sudo -E` if you want to keep environment variables across your sudo user and root. Example:

```
sudo -E docker run hello-world
```

From the docs on `sudo`:

```
-E, --preserve-env
             Indicates to the security policy that the user wishes to reserve their
             existing environment variables.  The security policy may eturn an error
             if the user does not have permission to preserve the environment.
```

**Comment by igorvpcleao** [comment]
```
[ec2-user@ip-xx-xx-xxx-xxx ~]$ sudo -E docker run hello-world
sudo: docker: command not found
```

**Comment by igorvpcleao** [comment]
Hey guys,
I gave up. It seems easy to start working with a Ubuntu Server.

Thanks for your support.

Should I keep the issue still open in case of someone find a solution?

**Comment by rgbkrk** [comment]
Thanks for giving it a go! You can leave it open. It sounds like @carolynvs was going to try to out the AMI as well, so if we find a solution we'll post it for all.

**Comment by carolynvs** [comment]
Sorry, I wasn't able to reproduce this. I'll close for now and please reopen if you have more steps to reproduce.

**Comment by Dhruvansh1** [comment]
After running these command getting these error:
1. sudo -E docker run hello-world
   **Cannot connect to the Docker daemon. Is 'docker -d' running on this host?**
2. docker run hello-world
**Cannot connect to the Docker daemon. Is 'docker -d' running on this host?**


not able to find out the solution. please help me
